// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpinLab.Api.Data;

#nullable disable

namespace SpinLab.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206071826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SpinLab.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Butterfly",
                            Category = "Raquetas",
                            Image = "https://deporteka.com.co/wp-content/uploads/2022/05/35861_01-600x600.webp",
                            Name = "Raqueta Butterfly Timo Boll ALC",
                            Price = 850000m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Brand = "DHS",
                            Category = "Raquetas",
                            Image = "https://revspin.net/images/blade/dhs-hurricane-301.jpg",
                            Name = "Raqueta DHS Hurricane 301",
                            Price = 620000m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Butterfly",
                            Category = "Pelotas",
                            Image = "https://revspin.net/images/balls/butterfly-3-star-40-plus-poly.jpg",
                            Name = "Pelotas Butterfly 40+ (6 unidades)",
                            Price = 78000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Brand = "DHS",
                            Category = "Gomas",
                            Image = "https://revspin.net/images/rubber/dhs-neo-hurricane-3-provincial-blue-sponge.jpg",
                            Name = "Goma DHS Hurricane 3 Neo",
                            Price = 145000m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Stiga",
                            Category = "Mesas",
                            Image = "https://images.weserv.nl/?url=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F715H6LW4MpL.jpg&w=640&q=100&output=webp",
                            Name = "Mesa de Tenis de Mesa Stiga Advantage",
                            Price = 1850000m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Butterfly",
                            Category = "Accesorios",
                            Image = "https://www.rocayaltura.co/4739-large_default/estuche-butterfly-2-raquetas.jpg",
                            Name = "Estuche Butterfly Doble",
                            Price = 98000m,
                            Rating = 4.4000000000000004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
